graph TD
  Main[Main/Accept] --> CH1[ClientHandler 1 - Thread]
  Main --> CHn[ClientHandler N - Thread]
  Main --> LoggerInit[TSLog init]
  subgraph Sync[Mecanismos]
    M1[mutex clients_mutex]
    LM[mutex logger]
  end
  CH1 --> M1
  CHn --> M1
  CH1 --> LM
  CHn --> LM
  Main --> LM